### ISSUE TITLE
How fast is this algorithm

### ISSUE THREAD

**Issue by guangtugao** [agshumate/Liftoff#13] opened 2020-06-28 15:02 UTC
Thank you for making this tool!
I'm lifting annotations of a fish genome assembly from RefSeq to a new assembly I recently generated for the same species. In about half an hour, the program finished the step of "aligning features". Now it has been almost 12 hours, it is still working on "lifting features" step. Is this normal or the program runs into a dead loop? How fast is this algorithm?
Regards,
Guangtu

**Comment by agshumate** [comment] 2020-06-28 16:42
Hi Guangtu. It should not be taking that long. Are there any features in your gff file besides genes, transcripts/mRNA, exons/CDS?

**Comment by guangtugao** [comment] 2020-06-28 16:57
Thanks, Alaina, for the quick reply!
Yes, there are ncRNA, tRNA, rRNA as well. Right now, these extra features are not important. Should I remove them from the original gff file?
Thanks,
Guangtu

**Comment by agshumate** [comment] 2020-06-28 17:06
Those should not be causing a problem. Sometimes "region" features or similar which span whole chromosomes cause long run times due to the algorithm comparing features that mapped to overlapping intervals. These region features overlap every other feature causing many comparisons. Is the data you are working with publicly available so i can test it?

**Comment by guangtugao** [comment] 2020-06-28 17:15
Yes, there are regions. They must cause the problems. The genome information is in NCBI: https://www.ncbi.nlm.nih.gov/assembly/GCF_002163495.1. Thank you for the help!
Guangtu

**Comment by agshumate** [comment] 2020-06-28 17:17
I recommend trying without the "region" features and  seeing if that improves the run time. If not, please do let me know and I will look into it

**Comment by guangtugao** [comment] 2020-06-28 23:17
Hi Alaina,
t looks like the program runs normally with the gff file only having features of genes, transcripts/mRNA, exons and CDS. Now I feel the program takes too much time at the step of "mapping unplaced genes". The reference assembly has 131,931 unplaced sequences, but no all of them have features of genes, transcripts/mRNA, exons and CDS, which means some _genes.fa files are empty. Does this cause the issue?
Thanks,
Guangtu

**Comment by agshumate** [comment] 2020-06-28 23:36
are you including all 131,931 sequences in the unplaced.txt? if so, remove the ones that do not have any features to lift over

**Comment by guangtugao** [comment] 2020-06-29 02:25
Hi Alaina,

It almost reached the end but the program crashed. Here is the output from the program:
extracting features
2020-06-28 21:15:52,255 - INFO - Populating features
2020-06-28 21:19:18,691 - INFO - Populating features table and first-order relations: 1750522 features
2020-06-28 21:19:18,691 - INFO - Updating relations
2020-06-28 21:19:35,691 - INFO - Creating relations(parent) index
2020-06-28 21:19:36,750 - INFO - Creating relations(child) index
2020-06-28 21:19:38,071 - INFO - Creating features(featuretype) index
2020-06-28 21:19:39,043 - INFO - Creating features (seqid, start, end) index
2020-06-28 21:19:40,265 - INFO - Creating features (seqid, start, end, strand) index
2020-06-28 21:19:41,575 - INFO - Running ANALYZE features
aligning features
lifting features
mapping unaligned features to whole genome
aligning features
lifting features
mapping unplaced genes
aligning features
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ggao/miniconda2/envs/py3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ggao/Programs/liftoff/align_features.py", line 54, in align_subset
    if target_chroms[index] == target_fasta_name:
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ggao/Programs/liftoff/liftoff.py", line 121, in <module>
    main()
  File "/home/ggao/Programs/liftoff/liftoff.py", line 91, in main
    children_features, parent_order,minimap2_path,inter_files)
  File "/home/ggao/Programs/liftoff/liftover_types.py", line 63, in map_unplaced_genes
    reference_fasta,minimap2_path,inter_files, True)
  File "/home/ggao/Programs/liftoff/align_features.py", line 24, in align_features_to_target
    for result in pool.imap_unordered(func, np.arange(0,len(ref_chroms))):
  File "/home/ggao/miniconda2/envs/py3/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
IndexError: list index out of range

Thanks,
Guangtu

**Comment by agshumate** [comment] 2020-06-29 17:13
Hi, i have found the source of this bug and merged in a fix. the latest version (1.1.1) should not give you this error anymore

**Comment by guangtugao** [comment] 2020-06-29 19:08
Yes, it works this time. However, it seems there is a bug in generating the output. Below is an example:
omya01  Liftoff gene    2471622 2473229 .       +       .       ID=gene49531;Dbxref=GeneID:110513485;Name=LOC110513485;end_range=16323,.;
omya05  Liftoff mRNA    1674933 1676543 .       +       .       ID=rna78486;Parent=gene49531;Dbxref=GeneID:110513485,Genbank:XM_021593292

The mRNA is in omya05, but its parent gene is in omya01. It shouldn't be, right?

Thanks,
Guangtu

**Comment by agshumate** [comment] 2020-06-29 19:31
there may be a problem with the input gff does not correctly associate the mRNA with the gene as its parent causing them to be lifted over separately. if possible could you please send the gff entry of these two features in reference annotation

**Comment by guangtugao** [comment] 2020-06-29 19:41
This is a gene in a unplaced sequence:

NW_018547694.1  Gnomon  gene    14716   16323   .       -       .       ID=gene49531;Dbxref=GeneID:110513485;Name=LOC110513485;end_range=16323,.;gbkey=Gene
NW_018547694.1  Gnomon  mRNA    14716   16323   .       -       .       ID=rna78486;Parent=gene49531;Dbxref=GeneID:110513485,Genbank:XM_021593292.1;Name=XM

**Comment by agshumate** [comment] 2020-06-29 19:45
if you could provide me a link to the full gff file you are using that would be very helpful

**Comment by guangtugao** [comment] 2020-06-29 19:48
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/8022/100/GCF_002163495.1_Omyk_1.0/GCF_002163495.1_Omyk_1.0_genomic.gff.gz

**Comment by agshumate** [comment] 2020-06-29 19:52
I cannnot find gene49531 or rna78486 in that file

**Comment by guangtugao** [comment] 2020-06-29 20:08
Just found out that RefSeq updated the format in Dec. 2019. I used the old version. As we are the main contributor to this assembly, I know there is no major change in content (the accession is the same). However the ID gene49531 is updated to gene-LOC110513485 and rna78486 becomes rna-XM_021593292.1. The old version is attached.
Thanks,
Guangtu

**Comment by agshumate** [comment] 2020-06-29 20:33
do you have a link to the old version?

**Comment by guangtugao** [comment] 2020-06-29 21:06
I couldn't find the old version now.

**Comment by agshumate** [comment] 2020-06-29 21:14
okay. please use the new version and let me know if the problem persists. My suspicion is that either gene49531 or rna78486  was not a unique identifier and the parent/child relationship between these features was messed up as a result

**Comment by guangtugao** [comment] 2020-06-30 13:10
Both gene49531 and rna78486 are unique identifiers. This should not be a problem and it is not difficult to check. Please note the problem occurs when the program works on the unplaced genes. For this species, omya01 and omya05 have a pair of homeologous regions. Is that possible that this is a result of non-unique mapping of either the gene sequence or the transcript sequence?

**Comment by agshumate** [comment] 2020-06-30 16:56
Hi, I'm sorry I was not able to check that on my end since I do not have the gff file. the gene sequence and the transcript sequence should not be mapping separately. are you using the -chroms option?

**Comment by guangtugao** [comment] 2020-06-30 17:06
> Hi, I'm sorry I was not able to check that on my end since I do not have the gff file. the gene sequence and the transcript sequence should not be mapping separately. are you using the -chroms option?

Yes, I used -chroms option. I tried to attach the old version gff file, but it was failed because the file is larger than 10MB. Trust me the identifiers are unique and I have been using this file in many other works without any problem. As you the transcript and gene are not mapped separately, is it possible that the gene sequence got two perfect matches in both chromosomes and your program just accidentally pick a wrong one? Thanks!

**Comment by agshumate** [comment] 2020-06-30 17:33
Yes that is possible, but it should have only picked one. are both gene49531 rna78486 in the intermediate file titled unplaced_genes.fa ?

**Comment by guangtugao** [comment] 2020-06-30 18:00
Good questions! Now we seem to find the problem. The unplaced_genes.fa file in the temp folder contains only one gene (gene52480) abd the corresponding sam file only has this gene mapping. However, my input for the option of -unplaced contains all the unplaced sequences that have gene annotations.
[files2check.zip](https://github.com/agshumate/Liftoff/files/4853651/files2check.zip)

**Comment by agshumate** [comment] 2020-06-30 19:18
indeed that does seem to be the problem. ive just committed a fix for this. i recommend removing everything in the intermediate files directory and trying again. thank you very much for your patience and again let me know if you have further trouble

**Comment by guangtugao** [comment] 2020-06-30 19:39
> indeed that does seem to be the problem. ive just committed a fix for this. i recommend removing everything in the intermediate files directory and trying again. thank you very much for your patience and again let me know if you have further trouble

I actually ran version 1.1.1 and got the above problem. Did you make changes just today or late yesterday? By the way, can you verify the format of my file NW_with_genes.txt (one sequence name per row) for the  -unplaced option is in the right format? 

Thanks,
Guangtu

**Comment by agshumate** [comment] 2020-06-30 19:43
i just made changes to v1.1.2 that should fix this issue. your file is in the correct format

**Comment by guangtugao** [comment] 2020-06-30 21:59
> i just made changes to v1.1.2 that should fix this issue. your file is in the correct format

Unfortunately, the problem with gene ID is still there. Sorry.

**Comment by guangtugao** [comment] 2020-06-30 22:06
> > i just made changes to v1.1.2 that should fix this issue. your file is in the correct format
> 
> Unfortunately, the problem with gene ID is still there. Sorry.

It seems this is a general bug. After I manually changed the chromosome number for gene49531, I found another one with the same problem with the validation.

**Comment by agshumate** [comment] 2020-06-30 22:33
can you please copy paste your chroms.txt file?

**Comment by guangtugao** [comment] 2020-06-30 22:48
> can you please copy paste your chroms.txt file?
Attached

[chrs.csv.zip](https://github.com/agshumate/Liftoff/files/4854725/chrs.csv.zip)

**Comment by guangtugao** [comment] 2020-06-30 23:46
Actually, you can do the test yourself. All files are available in NCBI from this link: https://www.ncbi.nlm.nih.gov/assembly/?term=Oncorhynchus+mykiss. The reference is Omyk_1.0 and the target is USDA_OmykA_1.0.
Thanks,
Guangtu

**Comment by agshumate** [comment] 2020-07-01 00:03
great! i am running the test now and will follow up soon

**Comment by agshumate** [comment] 2020-07-01 14:43
hi there. I am still unable to reproduce this bug with the files at that link. Is the USDA_OmykA_1.0 assembly the same one you are using just with different chromosome names? When I ran the test using this annotation ftp://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/8022/100/GCF_002163495.1_Omyk_1.0/GCF_002163495.1_Omyk_1.0_genomic.gff.gz

The gene and mRNA in question map to the same sequence which is also unplaced 
JAAXML010000451.1   Liftoff gene    60391   62005   .   +   .   ID=gene LOC110513485;Dbxref=GeneID:110513485;Name=LOC110513485;       
JAAXML010000451.1   Liftoff mRNA    60391   62005   .   +   .   ID=rna-XM_021593292.1;Parent=gene-LOC110513485

If there is a way for you to share your exact gff file you are using with me, perhaps via our ftp site or some other means, i will happily run the test again in hopes of reproducing this bug

**Comment by guangtugao** [comment] 2020-07-01 15:10
Good to know you didn't get the issue I got. I'll try to send the whole file in three pieces here. Can you show me your command line command to run this particular pair of assemblies? Thanks!
[GCF_002163495.1_Omyk_1.0_genomic.gffaa.zip](https://github.com/agshumate/Liftoff/files/4858673/GCF_002163495.1_Omyk_1.0_genomic.gffaa.zip)

**Comment by guangtugao** [comment] 2020-07-01 15:10
Second piece
[GCF_002163495.1_Omyk_1.0_genomic.gffab.zip](https://github.com/agshumate/Liftoff/files/4858675/GCF_002163495.1_Omyk_1.0_genomic.gffab.zip)

**Comment by guangtugao** [comment] 2020-07-01 19:09
Third
[GCF_002163495.1_Omyk_1.0_genomic.gffac.zip](https://github.com/agshumate/Liftoff/files/4858683/GCF_002163495.1_Omyk_1.0_genomic.gffac.zip)


> hi there. I am still unable to reproduce this bug with the files at that link. Is the USDA_OmykA_1.0 assembly the same one you are using just with different chromosome names? When I ran the test using this annotation ftp://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/8022/100/GCF_002163495.1_Omyk_1.0/GCF_002163495.1_Omyk_1.0_genomic.gff.gz
> 
> The gene and mRNA in question map to the same sequence which is also unplaced
> JAAXML010000451.1 Liftoff gene 60391 62005 . + . ID=gene LOC110513485;Dbxref=GeneID:110513485;Name=LOC110513485;
> JAAXML010000451.1 Liftoff mRNA 60391 62005 . + . ID=rna-XM_021593292.1;Parent=gene-LOC110513485
> 

Yes, the genome assembly is the same with different chromosome names. I used local ID and NCBI uses the standard accessions. The gff you used is the right one.  Thanks!

**Comment by agshumate** [comment] 2020-07-02 00:57
python liftoff.py -r GCF_002163495.1_Omyk_1.0_genomic.fna -t GCA_013265735.1_USDA_OmykA_1.0_genomic.fna -g GCF_002163495.1_Omyk_1.0_genomic_filtered.gff -unplaced unplaced.txt -chroms chroms.txt -o test.gff -p 29

This is the command i used. I first filtered the gff file for only genes and their transcripts/exons/cds etc  with 
grep GeneID GCF_002163495.1_Omyk_1.0_genomic.gff > GCF_002163495.1_Omyk_1.0_genomic_filtered.gff

**Comment by guangtugao** [comment] 2020-07-02 01:49
Hi is the my command:

src=Annotation/liftoff
python /home/ggao/Programs/liftoff/liftoff.py \
        -t "$src"/arlee_genome_v6_mit.fa \
        -r "$src"/GCF_002163495.1_Omyk_1.0_genomic_withGenes.fa \
        -g "$src"/GCF_002163495.1_Omyk_1.0_genomic_noExtra.gff \
        -chroms "$src"/chrs.csv -p 30 \
        -o arlee_genome_v6_mit_liftoff_noExtra.gff \
        -u noExtra_unmapped_features.txt \
        -a 0.5 -s 0.5 \
        -unplaced "$src"/NW_with_genes.txt \
        -copies -sc 1.0 \
        -m /home/ggao/miniconda2/envs/py3/bin/minimap2 \
        -dir temp
You see I do have the -copies option. I saw there is another issue with this option.

**Comment by agshumate** [comment] 2020-07-02 02:05
ah i see. yes i have just fixed an issue related to the copies option. this hopefully fixes your problem too

**Comment by guangtugao** [comment] 2020-07-02 13:24
With the new version, I got the following error message when I run the program. Another bug?

Traceback (most recent call last):
  File "/home/ggao/Programs/liftoff/liftoff/liftoff.py", line 1, in <module>
    from liftoff import write_new_gff, liftover_types
  File "/home/ggao/Programs/liftoff/liftoff/liftoff.py", line 1, in <module>
    from liftoff import write_new_gff, liftover_types
ImportError: cannot import name write_new_gff

**Comment by agshumate** [comment] 2020-07-02 13:52
the package structure changed in this version to make it easier to run. so you will need to run python setup.py develop first and then you should be able to run the program simply by calling 'liftoff'. The install steps in the README reflect this change

**Comment by skyungyong** [comment] 2020-07-02 17:59
Hi! I am having the same issue when running python liftoff.py, after python setup.py develop --user

**Comment by agshumate** [comment] 2020-07-02 18:04
try running it just as 
liftoff

**Comment by skyungyong** [comment] 2020-07-02 18:47
where the executable would be?
liftoff
-bash: liftoff: command not found

**Comment by agshumate** [comment] 2020-07-02 18:57
I am not sure for your particular setup. perhaps a better option would be running with the --prefix option to specify where you want the executable 
python setup.py install --prefix <dir> 
then the executable will be in <dir>/bin

**Comment by guangtugao** [comment] 2020-07-02 19:53
> where the executable would be?
> liftoff
> -bash: liftoff: command not found

In my case it is in the bin directory of my conda environment. Just type "which liftoff" to find it.

**Comment by LeebanY** [comment] 2020-07-03 16:47
Hi,
Just wanted to add that I'm having a similar issue. I've used liftoff to generate gff files for 2 genomes already; it worked like a charm and only took a couple of hours. However, I'm trying to do the exact same thing for 2 other genomes (same genus, same size genome and using the same reference) and it's been running for a few days now...I'm not sure what I've done wrong. I filtered the genome out for unnecessary features as you suggested, but this hasn't worked either. I'm just confused as to why the same parameters work fine for one set of genomes, but not for the other. Do you have any suggestions for what  I should try?

Thanks so much for your help,
L

**Comment by agshumate** [comment] 2020-07-03 16:53
Hi,
I merged in a few changes yesterday which should fix this problem.  If you could update to v1.2.0 and let me know if the issue persists, that would be great. Note that by default now only gene features and their children will be lifted over and other features should be specified with the -f option.

**Closed** 2020-07-05 22:45 UTC
